### ISSUE TITLE
Woo shop buttons take default of all others

### ISSUE THREAD

**Issue by christiebizbudding** [maithemewp/mai-theme-engine#38]
Whatever the styling of the Woo buttons are on the shop page, all other buttons (hardcoded) take on that styling

**Comment by JiveDig** [comment]
probably from:
.woocommerce a.button

May need to do:
.woocommerce .content a.button

That's quite specific, but then it won't break other buttons outside of the content.

Maybe just:
.content a.button

would do it?

**Comment by JiveDig** [comment]
@christiebizbudding Can you explain to me how i can easily recreate this bug on my local?

**Comment by christiebizbudding** [comment]
If you put a section hardcoded in a file like functions.php that has a button in it...then go to the Woo shop page, the hardcoded button takes on the styling of the Woo buttons (if the .button class styling is different from woo button styling)

**Comment by JiveDig** [comment]
Ah i see it now. I added a button in a text widget in the footer. Interesting.

**Comment by JiveDig** [comment]
This should be fixed in https://github.com/maithemewp/mai-theme-engine/commit/293c9cba2880e377e7c038dd4b77fa11e0b391fb

And definitely Mai Colors works correctly now:
<img width="790" alt="screen shot 2018-11-28 at 2 22 35 pm" src="https://user-images.githubusercontent.com/540990/49176562-13663f00-f319-11e8-90a4-6e0197eb297a.png">
